name: ganglong_shop_app
description: Digital product experts around you

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.2+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  flutter_swiper: ^1.1.6
  dio: ^2.1.13
  provider: ^3.0.0+1
  flutter_screenutil: ^0.5.3
  extended_image: '0.6.5'
  extended_image_library: '0.1.8'
  path_provider: ^1.2.0
  fluro: ^1.5.1
  smooth_star_rating: ^1.0.3
  sqflite: ^1.1.6
  fluttertoast: ^3.1.3
  loading_indicator: ^1.1.0
  get_it: ^3.0.1
  flutter_custom_dialog: ^1.0.0
  crypto: ^2.1.3
  image_picker: ^0.6.1+10
  fake_wechat: ^0.3.3
  image: ^2.1.8
  flutter_webview_plugin: "0.3.10"#ios:ok
  url_launcher: ^5.2.5
  curved_navigation_bar: ^0.3.1
  flutter_staggered_animations: ^0.1.2
  flutter_des: ^1.1.0
  fake_alipay: ^0.2.3
  flutter_downloader: ^1.3.3
  permission_handler: ^4.0.0
  open: '1.1.0'
  open_file: ^2.1.1
  package_info: ^0.4.0+12
  flutter_web_view: ^0.0.6
  flutter_ios_dark_mode: ^0.0.1
  open_appstore: ^1.0.2
  waterfall_flow: ^0.1.3
dev_dependencies:
  json_model: ^0.0.2
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - static_images/qq_logo.png
    - static_images/wechat_logo.png
    - static_images/alpay_logo.png
    - static_images/qq_logo_black.png
    - static_images/wechat_logo_black.png
    - static_images/alpay_logo_black.png
    - static_images/without_order.png
    - static_images/without_carts.png
    - static_images/without_address.png
    - static_images/without_user_coupon.png
    - static_images/without_evaluate.png
    - static_images/wechat_friend_circle_logo.png
    - static_images/wechat_friend_logo.png
    - static_images/all_class_preview_logo.png
    - static_images/web_view_loading.png
    - static_images/wx_first_top1_0812.jpg
    - static_images/wx_first_top2_0812.jpg
    - static_images/wx_first_top1_20200208.jpg
    - static_images/wx_first_top2_20200208.png
    - static_images/ketlle_goods_b1.png
    - static_images/ketlle_goods_b1.jpg
    - static_images/without_search_goods.png
    - static_images/order_state_0.png
    - static_images/order_state_2.png
    - static_images/order_state_3.png
    - static_images/order_state_4.png
    - static_images/order_state_5.png
    - static_images/order_state_6.png
    - static_images/order_state_7.png
    - static_images/order_state_8.png
    - static_images/WxAppApiPayment.png
    - static_images/AppAliPayment.png
    - static_images/TestPayment.png
    - static_images/logo_320.png
    - static_images/start_img.jpg
    - static_images/update_img.png
    - static_images/update_loading.png
    - static_images/hot_goods_head.png
    - static_images/middle_button.png
    - static_images/without_coupon.png
    - static_images/wx_icbc_icon_20190813.png
    - static_images/wx_conpou_icon_20190813.png
    - static_images/user_not_logon_head.png
    - static_images/browser-404.png
    - static_images/boot_img1.jpeg
    - static_images/boot_img2.jpeg
    - static_images/boot_img3.jpeg
    - static_images/boot_img4.jpeg
    - static_images/boot_img5.jpeg
    - static_jsons/address_options.json


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
